language: cpp

compiler:
  - gcc

before_install:
  - sudo apt-get update -qq
  - sudo apt-get install libboost-all-dev flex bison libssl-dev libpq-dev libmysqlclient-dev libedit-dev libyajl-dev

before_script:
  - mkdir build
  - cd build
  - cmake ..

script:
  - make
  - sudo make install
  - icinga2 --version
