dist: xenial
sudo: false

language: cpp

cache: ccache

addons:
  apt:
    sources:
      - sourceline: 'deb http://packages.icinga.com/ubuntu icinga-xenial main'
        key_url: 'https://packages.icinga.com/icinga.key'
    packages:
      - libboost1.67-icinga-all-dev
      - flex
      - bison
      - libssl-dev
      - libpq-dev
      - libmysqlclient-dev
      - libedit-dev
before_script:
  - mkdir build
  - cd build
  - cmake .. -DCMAKE_BUILD_TYPE=Debug -DCMAKE_INSTALL_PREFIX=/tmp/icinga2 -DICINGA2_PLUGINDIR=/tmp/icinga2/sbin

script:
  - make
  - make test
  - make install
  - /tmp/icinga2/sbin/icinga2 --version
  - /tmp/icinga2/sbin/icinga2 daemon -C -DRunAsUser=$(id -u -n) -DRunAsGroup=$(id -g -n)
