site_name: Icinga 2
docs_dir: doc
dev_addr: 0.0.0.0:8000
pages:
- [1-about.md, About Icinga 2]
- [2-getting-started.md, Getting Started]
- [3-monitoring-basics.md, Monitoring Basics]
- [4-configuring-icinga-2.md, Configuring Icinga 2]
- [5-object-types.md, Object Types]
- [6-icinga-template-library.md, Icinga Template Library]
- [7-monitoring-remote-systems.md, Monitoring Remote Systems]
- [8-cli-commands.md, CLI Commands]
- [9-addons-plugins.md, Addons and Plugins]
- [10-alternative-frontends.md, Alternative Frontends]
- [11-livestatus.md, Livestatus]
- [12-troubleshooting.md, Troubleshooting]
- [13-upgrading-icinga-2.md, Upgrading Icinga 2]
- [14-migrating-from-icinga-1x.md, Migrating from Icinga 1.x]
- [15-language-reference.md, Language Reference]
- [16-library-reference.md, Library Reference]
- [17-appendix.md, Appendix]
theme: readthedocs
markdown_extensions: [smarty]
extra_javascript: [scroll.js]
include_search: true
