site_name: Icinga 2
docs_dir: doc
dev_addr: 0.0.0.0:8000
pages:
- [1-about.md, About Icinga 2]
- [2-getting-started.md, Getting Started]
- [3-monitoring-basics.md, Monitoring Basics]
- [4-monitoring-remote-systems.md, Monitoring Remote Systems]
- [5-cli-commands.md, CLI Commands]
- [6-addons-plugins.md, Addons and Plugins]
- [7-livestatus.md, Livestatus]
- [8-troubleshooting.md, Troubleshooting]
- [9-migrating-from-icinga-1x.md, Migrating from Icinga 1.x]
- [10-language-reference.md, Language Reference]
- [11-library-reference.md, Library Reference]
- [12-object-types.md, Object Types]
- [13-icinga-template-library.md, Icinga Template Library]
- [14-appendix.md, Appendix]
theme: readthedocs
markdown_extensions: [smarty]
extra_javascript: [scroll.js]
include_search: true
