name: Docker image

on:
  pull_request: {}
  push:
    branches:
      - master
      - 'support/*'
  release:
    types:
      - published

concurrency:
  group: docker-${{ github.ref }}
  cancel-in-progress: true

jobs:
  docker:
    runs-on: ubuntu-latest

    steps:
      - name: Docker image
        uses: Icinga/docker-icinga2@master
        env:
          INPUT_TOKEN: '${{ github.token }}'
          DOCKER_HUB_PASSWORD: '${{ secrets.DOCKER_HUB_PERSONAL_TOKEN }}'
